language: python
python:
  - "3.5"  # 3.7 development branch
cache: pip

before_install:
  - pip install mysql-connector-python
  - pip install coveralls
install:
  - pip install -r requirements.txt
script:
   - coverage run test_script.py
after_success:
- codecov

# after_success:
#   - coveralls
# script:
#   - coverage run tests.py

# # Push the results back to codecov
